# Generated by Django 2.0.7 on 2018-07-24 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_load_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prezi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
