version: '3'

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - .:/src
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
